### ISSUE TITLE
Docker Install Error

### ISSUE THREAD

**Issue by hnisonoff** [gnina/gnina#151]
### Issue summary

I am using the Ubuntu Dockerfile provided but am getting an error related to cuDNN:
```
-- CUDA detected: 10.2
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at caffe/cmake/Cuda.cmake:237 (message):
  cuDNN version >=8 is required.
Call Stack (most recent call first):
  caffe/cmake/Cuda.cmake:264 (detect_cuDNN)
  caffe/cmake/Dependencies.cmake:87 (include)
  caffe/CMakeLists.txt:50 (include)


-- Configuring incomplete, errors occurred!
See also "/root/gnina/build/CMakeFiles/CMakeOutput.log".
See also "/root/gnina/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
The command '/bin/sh -c git clone https://github.com/gnina/gnina.git;     cd gnina; mkdir build; cd build;     cmake .. ;    make -j4 ; make install' returned a non-zero code: 2
```

### Steps to reproduce
`docker build -t gnina .`

### Your system configuration
Operating system: Ubuntu 16.04.6 LTS
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
I just added support for cudnn8 and haven't updated the dockerfile yet.  The check is actually overly agressive - cudnn7 should still work.  I've pushed a rollback of the check to allow version 7.

**Comment by hnisonoff** [comment]
Thanks for the quick reply! That helped but now I have another issue...

```
nvcc fatal   : Unsupported gpu architecture 'compute_80'
src/CMakeFiles/libmolgrid_shared.dir/build.make:185: recipe for target 'src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o' failed
make[5]: *** [src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
[ 28%] Building CUDA object src/CMakeFiles/libmolgrid_static.dir/grid_maker.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
src/CMakeFiles/libmolgrid_static.dir/build.make:185: recipe for target 'src/CMakeFiles/libmolgrid_static.dir/grid_maker.cu.o' failed
make[5]: *** [src/CMakeFiles/libmolgrid_static.dir/grid_maker.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1008: recipe for target 'src/CMakeFiles/libmolgrid_static.dir/all' failed
make[4]: *** [src/CMakeFiles/libmolgrid_static.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:981: recipe for target 'src/CMakeFiles/libmolgrid_shared.dir/all' failed
make[4]: *** [src/CMakeFiles/libmolgrid_shared.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/libmolgrid.dir/build.make:129: recipe for target 'libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build' failed
make[2]: *** [libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build] Error 2
CMakeFiles/Makefile2:710: recipe for target 'CMakeFiles/libmolgrid.dir/all' failed
make[1]: *** [CMakeFiles/libmolgrid.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
[  0%] Performing update step for 'libmolgrid'
[  0%] No patch step for 'libmolgrid'
[  0%] Performing configure step for 'libmolgrid'
-- Current git revision is 7b7633ef54bf9ee20f66b846f6296b3fe5088f7a
-- Found Boost: /usr/include (found version "1.65.1") found components: regex unit_test_framework program_options system filesystem iostreams
-- Found Boost: /usr/include (found version "1.65.1") found components: system filesystem python36
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework system
-- Configuring done
-- Generating done
-- Build files have been written to: /root/gnina/build/libmolgrid-prefix/src/libmolgrid-build
[  0%] Performing build step for 'libmolgrid'
[  1%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
src/CMakeFiles/libmolgrid_shared.dir/build.make:185: recipe for target 'src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o' failed
make[5]: *** [src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o] Error 1
CMakeFiles/Makefile2:981: recipe for target 'src/CMakeFiles/libmolgrid_shared.dir/all' failed
make[4]: *** [src/CMakeFiles/libmolgrid_shared.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/libmolgrid.dir/build.make:129: recipe for target 'libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build' failed
make[2]: *** [libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build] Error 2
CMakeFiles/Makefile2:710: recipe for target 'CMakeFiles/libmolgrid.dir/all' failed
make[1]: *** [CMakeFiles/libmolgrid.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c git clone https://github.com/gnina/gnina.git;     cd gnina; mkdir build; cd build;     cmake .. ;    make -j4 ; make install' returned a non-zero code: 2
```


Is it possible that my GPU is not supported? GTX 1080 Ti

**Comment by dkoes** [comment]
I think the issue is I've been keeping the build system up-to-date with newer card versions but not updated the dockerfiles appropriately.  If you don't mind running a newer operating system, the Dockerfile for ubuntu 22.04 is much cleaner:
```
#get CUDA 
FROM nvidia/cuda:11.7.0-devel-ubuntu22.04

# get packages 
WORKDIR /root
RUN apt update ; apt upgrade -y ; apt-get -y install build-essential git cmake wget libboost-all-dev libeigen3-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler libhdf5-dev libatlas-base-dev python3-dev librdkit-dev python3-numpy python3-pip python3-pytest openbabel libopenbabel-dev python3-openbabel

RUN git clone https://github.com/gnina/gnina.git; \
    cd gnina; mkdir build; cd build; \
    cmake -DCUDA_ARCH_NAME=All .. ;\
    make -j4 ; make install 
```

(I actually haven't finished building/testing this, but so far it seems to be working...)

**Comment by hnisonoff** [comment]
Thanks! Tried that but ran into issues:



```
Step 3/4 : RUN apt update ; apt upgrade -y ; apt-get -y install build-essential git cmake wget libboost-all-dev libeigen3-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler libhdf5-dev libatlas-base-dev python3-dev librdkit-dev python3-numpy python3-pip python3-pytest openbabel libopenbabel-dev python3-openbabel
 ---> Running in ffb4dba79414

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Err:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease' is not signed.
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://archive.ubuntu.com/ubuntu jammy InRelease' is not signed.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-updates InRelease' is not signed.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-backports InRelease' is not signed.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://security.ubuntu.com/ubuntu jammy-security InRelease' is not signed.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'git' has no installation candidate
E: Unable to locate package cmake
E: Unable to locate package wget
E: Unable to locate package libboost-all-dev
E: Unable to locate package libeigen3-dev
E: Unable to locate package libgoogle-glog-dev
E: Unable to locate package libprotobuf-dev
E: Unable to locate package protobuf-compiler
E: Unable to locate package libhdf5-dev
E: Unable to locate package libatlas-base-dev
E: Unable to locate package python3-dev
E: Unable to locate package librdkit-dev
E: Unable to locate package python3-numpy
E: Unable to locate package python3-pip
E: Unable to locate package python3-pytest
E: Unable to locate package openbabel
E: Unable to locate package libopenbabel-dev
E: Unable to locate package python3-openbabel
The command '/bin/sh -c apt update ; apt upgrade -y ; apt-get -y install build-essential git cmake wget libboost-all-dev libeigen3-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler libhdf5-dev libatlas-base-dev python3-dev librdkit-dev python3-numpy python3-pip python3-pytest openbabel libopenbabel-dev python3-openbabel' returned a non-zero code: 100
```

**Comment by dkoes** [comment]
Those errors don't make sense to me (the file works for me).  May there's an issue with copying and pasting.  Try the actual file:
https://github.com/gnina/gnina/blob/master/docker/ubuntu-22.04/Dockerfile

**Comment by hnisonoff** [comment]
I don't think it is a copying and pasting error. I am using your exact file with the same issue 

```
git clone https://github.com/gnina/gnina.git
cd gnina/docker/ubuntu-22.04/
docker build -t gnina .
```

**Comment by dkoes** [comment]
Maybe issues with your network or running out of space? Those are pretty standard packages apt can’t find…

**Comment by hnisonoff** [comment]
Yeah it is strange... the good news Is I was able to install with your Ubuntu18 version. Thanks for all the help!!
