### ISSUE TITLE
CMake error in v1.1

### ISSUE THREAD

**Issue by NikiKou** [gnina/gnina#263]
### Issue summary
cmake .. is ok on gnina
In make command, I get the following error: 

[  4%] Completed 'libmolgrid'
[  4%] Built target libmolgrid
[  6%] Built target caffeproto
[ 89%] Built target caffe
[ 89%] Linking CXX executable caffe
/usr/bin/ld: caffe: hidden symbol `__cudaLaunchKernel' in /usr/local/cuda-12.4/lib64/libcudart_static.a(cudart_static.o) is referenced by DSO
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/build.make:142: caffe/tools/caffe] Error 1
make[1]: *** [CMakeFiles/Makefile2:528: caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

the info for cmake ..
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 11.5.119
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-12.4 (found suitable version "12.4", minimum required is "11.0")
openbabel BINARY_DIR = /home/nikoletta/gnina/build
openbabel BINARY_DIR = /home/nikoletta/gnina/build
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel INTERFACE_INCLUDE_DIRECTORIES = /usr/local/include/openbabel3
openbabel NAME = openbabel
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SOURCE_DIR = /home/nikoletta/gnina
openbabel SOURCE_DIR = /home/nikoletta/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY)
libmolgrid will be fetched from git
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Found Python: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
-- CUDA detected: 11.5
-- Added CUDA NVCC flags for: sm_75
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.54") found components: system thread filesystem iostreams timer
-- Found libmolgrid: /home/nikoletta/gnina/build/external/include
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (found version "3.12.4")
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.7") found components: HL
-- CUDA detected: 11.5
-- Found cuDNN: ver. 9.0.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_75
-- Found Atlas: /usr/include/x86_64-linux-gnu
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.0")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found suitable version "3.10.12", minimum required is "3.0")
-- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found suitable version "1.21.5", minimum required is "1.7.1")
-- NumPy ver. 1.21.5 found (include: /usr/lib/python3/dist-packages/numpy/core/include)
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.58") found components: python310
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Caffe_ALL_DEFINITIONS -DUSE_CUDNN;-DWITH_PYTHON_LAYER
--
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.1-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.74)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. ..)
--   CUDA              :   Yes (ver. 11.5)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_75
--   cuDNN             :   Yes (ver. 9.0.0)
--
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.10.12)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.10.so (ver 3.10.12)
--   NumPy             :   /usr/lib/python3/dist-packages/numpy/core/include (ver 1.21.5)
--
-- Documentaion:
--   Doxygen           :   No
--   config_file       :
--
-- Install:
--   Install path      :   /usr/local
--
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nikoletta/gnina/build

### Your system configuration
Operating system: WSL2
Compiler: 
CUDA version (if applicable): 11.5 (i also have 12.4 but I defined 11.5)
CUDNN version (if applicable): 9
Python version: 3.10

**Comment by dkoes** [comment]
Not really sure, but it looks like your nvcc version is 11.5 and you are linking against 12.4.  I would try to maintain a consistent cuda version throughout.

**Comment by NikiKou** [comment]
Thanks, I uninstalled 11.5 and kept only 12.4 and it worked.
