### ISSUE TITLE
./gnina: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JonasLi-19** [gnina/gnina#301]
I use the pre-built binary gnina to do docking, my conda env contains:
```
python=3.10.13
pytorch=2.3.0
cuda-cudart               12.1.105                      0    nvidia                                                                                                     
cuda-cupti                12.1.105                      0    nvidia                                                                                                     
cuda-libraries            12.1.0                        0    nvidia                                                                                                     
cuda-nvrtc                12.1.105                      0    nvidia                                                                                                     
cuda-nvtx                 12.1.105                      0    nvidia                                                                                                     
cuda-opencl               12.6.77                       0    nvidia                                                                                                     
cuda-runtime              12.1.0                        0    nvidia                                                                                                     
cuda-version              12.6                          3    nvidia
```

My cuda is installed following the instruction in pytorch website:
`conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

Error:
./gnina: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

**Comment by JonasLi-19** [comment]
I have solved this issue, the problem is I didn't load the cuda in the .sh script when submitting the task to the server: 
module ava cuda
module load cuda/12.1
